openapi: 3.1.0
info:
  title: pulsepoint_rag_api_420423430685_us_east4_run_app
  description: Semantic search across PulsePoint's Confluence documentation for strategic context, roadmaps, and requirements
  version: 1.0.0
servers:
  - url: https://pulsepoint-rag-api-420423430685.us-east4.run.app
    description: Production Confluence RAG API
paths:
  /search:
    post:
      operationId: searchConfluence
      summary: Search Confluence documentation
      description: Perform semantic search across PulsePoint's Confluence documentation to find strategic context, roadmaps, requirements, and product information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Search query for Confluence documentation
                max_results:
                  type: integer
                  default: 10
                  description: Maximum number of results to return
              required:
                - query
            examples:
              ao_factors:
                summary: Search AO Factors documentation
                value:
                  query: "AO Factors adaptive optimization"
                  max_results: 15
              studio_features:
                summary: Search Studio capabilities
                value:
                  query: "Studio capabilities audience targeting HCP"
                  max_results: 12
      responses:
        '200':
          description: Successful search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        content:
                          type: string
                        title:
                          type: string
                        source_url:
                          type: string
                        similarity_score:
                          type: number
                  count:
                    type: integer