openapi: 3.1.0
info:
  title: PulsePoint Git Repository API - Final Working Version
  description: |
    Git repository API with only confirmed working endpoints.
    **26 repositories, 50,660 files, 64,058 functions**
    
  version: "1.0.0"

servers:
  - url: https://git-repository-api-420423430685.us-east4.run.app

paths:
  /:
    get:
      operationId: getGitApiStatus
      summary: Get API status
      responses:
        '200':
          description: API status
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
                  capabilities:
                    type: array
                    items:
                      type: string

  /repositories:
    get:
      operationId: listRepositories
      summary: List repositories
      parameters:
        - name: repository_name
          in: query
          schema:
            type: string
        - name: max_results
          in: query
          schema:
            type: integer
            default: 50
      responses:
        '200':
          description: Repository list
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_results:
                    type: integer
                  repositories:
                    type: array
                    items:
                      type: object

  /files/search:
    post:
      operationId: filesSearch
      summary: Search files by content, name, or language
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                search_content:
                  type: string
                  description: "Search within file content"
                file_name:
                  type: string
                language:
                  type: string
                repository_name:
                  type: string
                max_results:
                  type: integer
                  default: 100
      responses:
        '200':
          description: File search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_results:
                    type: integer
                  files:
                    type: array
                    items:
                      type: object

  /functions/search:
    post:
      operationId: functionsSearch
      summary: Search functions by name, class, or language
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                function_name:
                  type: string
                language:
                  type: string
                repository_name:
                  type: string
                class_name:
                  type: string
                max_results:
                  type: integer
                  default: 100
      responses:
        '200':
          description: Function search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_results:
                    type: integer
                  functions:
                    type: array
                    items:
                      type: object

  /github_code_search:
    post:
      operationId: github_code_search
      summary: Advanced code search with OR logic support
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: "Search terms (supports 'term1 OR term2')"
                repository_name:
                  type: string
                language:
                  type: string
                max_results:
                  type: integer
                  default: 50
              required:
                - query
      responses:
        '200':
          description: Code search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_results:
                    type: integer
                  matches:
                    type: array
                    items:
                      type: object

  # THE ONLY WORKING CORRELATION ENDPOINT
  /correlations/ticket:
    post:
      operationId: searchTicketCorrelations
      summary: Find Git-Jira ticket correlations (ONLY WORKING ENDPOINT)
      description: |
        **THE ONLY WORKING CORRELATION ENDPOINT**
        
        Tested with real data: 76 unique tickets have correlations
        Example working ticket IDs: ET-20392, DPD-1613, APPS-4946
        
        Do NOT use any other correlation operation names.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ticket_id:
                  type: string
                  description: "Jira ticket ID (e.g., ET-20392)"
                  example: "ET-20392"
                repository_name:
                  type: string
                  description: "Optional: filter by repository"
                max_results:
                  type: integer
                  default: 50
              required:
                - ticket_id
      responses:
        '200':
          description: Ticket correlation results
          content:
            application/json:
              schema:
                type: object
                properties:
                  query_type:
                    type: string
                  total_results:
                    type: integer
                  correlations:
                    type: array
                    items:
                      type: object
                      properties:
                        ticket_id:
                          type: string
                        source_repository:
                          type: string
                        reference_type:
                          type: string
                        context:
                          type: string
                        processed_at:
                          type: string
                  ticket_summary:
                    type: array
                    items:
                      type: object
                      properties:
                        ticket_id:
                          type: string
                        repository_count:
                          type: integer
                        repositories:
                          type: string

  /correlations/summary:
    get:
      operationId: correlationsSummary
      summary: Get overview of all ticket correlations
      description: "Shows all 76 tickets that have code correlations"
      responses:
        '200':
          description: Correlation summary with statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  query_type:
                    type: string
                  top_tickets_by_repos:
                    type: array
                    items:
                      type: object
                      properties:
                        ticket_id:
                          type: string
                        repository_count:
                          type: integer
                  total_correlations:
                    type: integer
                  total_unique_tickets:
                    type: integer