openapi: 3.1.0
info:
  title: PulsePoint Knowledge Layer v12.0 - Stable JIRA v4 Integration
  description: Revolutionary architecture with stable jira-api-v4-dual-mode integration replacing complex BigQuery calls. Enhanced reliability with preserved functionality for Confluence, Document360, GitHub, Mermaid.
  version: 12.0.0
servers:
  - url: https://us-east4-pulsepoint-datahub.cloudfunctions.net/knowledge-orchestrator-v12
    description: Knowledge Layer v12 - Stable JIRA v4 Integration (ACTIVE)

paths:
  /:
    get:
      operationId: healthCheckV12
      summary: Health check for v12 stable JIRA architecture
      description: Get API health status and stable JIRA v4 integration capabilities
      responses:
        '200':
          description: Health status showing v12 stable JIRA v4 features
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: "12.0-STABLE-JIRA-V4-INTEGRATION"
                  message:
                    type: string
                    example: "Knowledge Layer v12 - Stable JIRA v4 Integration"
                  status:
                    type: string
                    example: "healthy"

    post:
      operationId: searchWithStableJiraV4
      summary: Search with v12 stable JIRA v4 integration
      description: Revolutionary search leveraging stable jira-api-v4-dual-mode endpoint for maximum reliability.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: Natural language question with stable JIRA v4 support
                  example: "What are Kenan Akin's tickets in September 2025 including story points summary?"
                max_results:
                  type: integer
                  description: Maximum results from each data source
                  default: 50
              required:
                - question
      responses:
        '200':
          description: Comprehensive response with v12 stable JIRA v4 integration
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: "12.0-STABLE-JIRA-V4-INTEGRATION"
                  timestamp:
                    type: string
                    format: date-time
                  question:
                    type: string
                  jira_analysis:
                    type: object
                    description: JIRA analysis with v12 stable v4 integration
                    properties:
                      query_type:
                        type: string
                        enum: ["aggregation", "tickets"]
                      summary:
                        type: array
                        description: V12 ENHANCEMENT - Direct aggregation from stable v4 API
                        items:
                          type: object
                          properties:
                            product_manager:
                              type: string
                            total_tickets:
                              type: integer
                            total_points:
                              type: number
                      tickets:
                        type: array
                        description: Individual tickets from stable v4 API
                        items:
                          type: object
                          properties:
                            issue_key:
                              type: string
                            summary:
                              type: string
                            product_manager:
                              type: string
                            story_points:
                              type: number
                  confluence_analysis:
                    type: object
                    description: Confluence documentation analysis (preserved)
                  github_integration:
                    type: object
                    description: GitHub integration with Mermaid diagrams (preserved)
                  documentation:
                    type: array
                    description: Document360 technical documentation (preserved)
                  semantic_search:
                    type: object
                    description: V12 PRESERVED - Vector-based semantic search results
                  api_status:
                    type: object
                    description: Status of all integrated APIs with v12 stable JIRA