openapi: 3.1.0
info:
  title: PulsePoint Knowledge Layer API v2 - WORKING VERSION
  description: |
    Enhanced Knowledge Layer API with fully working JIRA integration. 
    Combines Confluence documentation with filtered JIRA tickets using proven working parameters.
    Version 2.2.0 with all filters tested and confirmed working.
  version: 2.2.0
servers:
  - url: https://pulsepoint-knowledge-layer-api-v2-420423430685.us-east4.run.app
    description: Production Knowledge Layer API v2 - FULLY WORKING JIRA INTEGRATION

paths:
  /:
    get:
      operationId: healthCheck
      summary: Health check
      description: Get API health status and enhanced capabilities
      responses:
        '200':
          description: Health status showing all working enhancements
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "PulsePoint Knowledge Layer API v2 - FULLY WORKING with enhanced JIRA filtering"
                  status:
                    type: string
                    example: "healthy"
                  version:
                    type: string
                    example: "2.2.0"
                  jira_integration:
                    type: string
                    example: "FULLY WORKING - sprint_date/release_date/assignee/reporter_name with partial matching"
                  enhancements:
                    type: array
                    items:
                      type: string
                    example: ["✅ WORKING: sprint_date filtering", "✅ WORKING: assignee partial matching"]
                  data_source:
                    type: string
                    example: "pulsepoint-datahub.rag_system.unified_content"

  /ask:
    post:
      operationId: askQuestion
      summary: Ask comprehensive product question - FULLY ENHANCED
      description: Ask product questions and get Confluence + JIRA analysis with working filters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: Your product question
                  example: "What are the AO epics in the current sprint for Bryan?"
                context:
                  type: string
                  description: Additional context (optional)
                  example: "quarterly planning"
                max_results:
                  type: integer
                  description: Maximum results to return
                  default: 10
              required:
                - question
      responses:
        '200':
          description: Comprehensive analysis with Confluence + filtered JIRA
          content:
            application/json:
              schema:
                type: object
                properties:
                  question:
                    type: string
                    description: Original question
                  context:
                    type: string
                    description: Context provided
                  confluence_analysis:
                    type: object
                    description: Confluence documentation analysis
                    properties:
                      answer:
                        type: string
                        description: Comprehensive answer from documentation
                      sources:
                        type: array
                        description: Source documents with similarity scores
                      confidence:
                        type: number
                        description: Confidence score (0-1)
                      total_sources_found:
                        type: integer
                  jira_analysis:
                    type: object
                    description: Enhanced JIRA ticket analysis with WORKING filters
                    properties:
                      filtering_applied:
                        type: string
                        example: "✅ WORKING: Enhanced filtering with sprint_date/release_date/assignee/reporter_name + partial matching"
                      search_terms:
                        type: array
                        description: Terms extracted for JIRA search
                      tickets_found:
                        type: integer
                        description: Total tickets found
                      tickets_relevant:
                        type: integer
                        description: Tickets passing 2+ filter requirement
                      project_key_used:
                        type: string
                        description: Project used for search (PROD, STUD, ET)
                      filters_applied:
                        type: object
                        description: Actual JIRA API parameters used
                      filter_breakdown:
                        type: object
                        properties:
                          stream_matches:
                            type: integer
                          product_matches:
                            type: integer
                          summary_matches:
                            type: integer
                          multi_filter_passes:
                            type: integer
                      tickets:
                        type: array
                        description: Top relevant tickets with URLs
                        items:
                          type: object
                          properties:
                            key:
                              type: string
                              example: "PROD-13141"
                            summary:
                              type: string
                            stream:
                              type: string
                            product:
                              type: string
                            assignee:
                              type: string
                            sprint_date:
                              type: string
                            release_date:
                              type: string
                            url:
                              type: string
                              example: "https://ppinc.atlassian.net/browse/PROD-13141"
                            relevance_reason:
                              type: string
                              description: Why this ticket is relevant
                  synthesis:
                    type: string
                    description: Combined analysis of Confluence + JIRA data
                  version:
                    type: string
                    example: "2.2.0"

  /search:
    post:
      operationId: searchConfluence
      summary: Search Confluence only (legacy v1 endpoint)
      description: Search only Confluence documentation using BigQuery vector similarity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                max_results:
                  type: integer
                  default: 10
      responses:
        '200':
          description: Confluence search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        chunk_id:
                          type: string
                        content:
                          type: string
                        title:
                          type: string
                        source_url:
                          type: string
                        similarity_score:
                          type: number
                  total_results:
                    type: integer
                  confidence:
                    type: number