openapi: 3.1.0
info:
  title: PulsePoint Knowledge Layer API v5
  description: Product-focused knowledge API with aggregation support, roadmap queries, and intelligent filtering - defaults to Product-driven work
  version: 5.0.0
servers:
  - url: https://us-east4-pulsepoint-datahub.cloudfunctions.net/knowledge-layer-v5
    description: Production Knowledge Layer API v5 - PRODUCT FOCUSED

paths:
  /:
    get:
      operationId: healthCheck
      summary: Health check and API status
      description: Get API health status and available features
      responses:
        '200':
          description: API health information
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  version:
                    type: string
                    example: "5.0-ROADMAP-ENHANCED"
                  message:
                    type: string
                    example: "Knowledge Layer v5 - Fixed Data Source Integration + Intelligent Synthesis"
                  features:
                    type: array
                    items:
                      type: string
                    example: ["DEFAULT: Product-driven work filter for all JIRA queries", "ENHANCED: Aggregation queries with counts and sums", "ENHANCED: 12-month roadmap queries with chronological timeline", "ENHANCED: sprint_date and release_date organization", "ENHANCED: JQL links for JIRA sources", "FIXED: All data sources use actual search", "ENHANCED: OpenAI-powered synthesis"]

  /:
    post:
      operationId: askQuestion
      summary: Query the knowledge layer for comprehensive product information
      description: Query JIRA, Confluence, GitHub, Document360 with intelligent synthesis. Defaults to Product-driven work. Enhanced roadmap queries by sprint/release dates, aggregation queries with counts/sums.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: The question to ask about PulsePoint products, features, or processes
                  example: "Please provide a detailed AO Product roadmap including the factors"
                session_id:
                  type: string
                  description: Optional session ID for conversation continuity
                  example: "session_1758894739_327cd516"
                conversation_history:
                  type: array
                  description: Optional conversation history for context
                  items:
                    type: object
                max_results:
                  type: integer
                  description: Maximum number of results to return
                  default: 50
                  example: 50
              required:
                - question
      responses:
        '200':
          description: Comprehensive response with synthesized information from all data sources
          content:
            application/json:
              schema:
                type: object
                properties:
                  synthesis_response:
                    type: object
                    properties:
                      response:
                        type: string
                        description: Comprehensive synthesized response combining all data sources
                        example: "## Adaptive Optimization (AO) Product Roadmap\n\n#### **April 2025**\n- **Sprint Date**: April 2025\n  - **Release Date**: May 2025\n    - **Epic**: [AO Phase 1] Tactic optimization. Relocate audience optimization\n      **Assignee**: Roman Kuzmych\n      [View Ticket](https://ppinc.atlassian.net/browse/PROD-12555)\n\n#### **May 2025**\n- **Sprint Date**: May 2025\n  - **Release Date**: June 2025\n    - **Epic**: [AO Phase 1.2] Make Audience Quality look like adaptive optimization package\n      **Assignee**: Roman Kuzmych\n      [View Ticket](https://ppinc.atlassian.net/browse/PROD-12842)\n\n### Sources:\n- [JIRA Epics & Tickets](https://ppinc.atlassian.net/issues/?jql=key%20in%20(PROD-12555,PROD-12842))"
                      sources:
                        type: array
                        items:
                          type: string
                        description: List of data sources used
                        example: ["JIRA API", "Confluence API", "GitHub API", "Document360 API"]
                      synthesis_method:
                        type: string
                        description: Method used for synthesis
                        example: "openai_gpt4o_mini"
                      session_id:
                        type: string
                        description: Session ID for conversation continuity
                        example: "session_1758894739_327cd516"
                      version:
                        type: string
                        description: API version
                        example: "5.0-PRODUCT-FOCUSED"
                      api_status:
                        type: object
                        properties:
                          data_sources_queried:
                            type: integer
                            example: 4
                          data_sources_successful:
                            type: integer
                            example: 2
                          jira_query_success:
                            type: boolean
                            example: false
                          confluence_api_success:
                            type: boolean
                            example: true
                          github_api_success:
                            type: boolean
                            example: true
                          document360_api_success:
                            type: boolean
                            example: false
                          confluence_sources:
                            type: integer
                            example: 0
                          github_repos:
                            type: integer
                            example: 3
                          document360_articles:
                            type: integer
                            example: 0
        '400':
          description: Bad request - missing or invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No question provided"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error: Failed to retrieve JIRA data"
                  version:
                    type: string
                    example: "5.0-ROADMAP-ENHANCED"
                  timestamp:
                    type: string
                    example: "2025-09-26T13:53:21.930322338Z"
